name: Build React App
on:
  push:
    branches:
      - atomic
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        
      - name: Check Node v
        run: node -v

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Npm Install
        run: |
          npm install
      - name: Npm Build
        run: |
          npm run build
      - name: Deploy to S3
        uses: T-Notes/Tnote-FrontEnd@atomic
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: 'dist'
